apiVersion: v2
name: spark-operator
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: spark-operator
    version: 1.3.1
    repository: https://kubeflow.github.io/spark-operator